### ISSUE TITLE
Question: Possible to add this to Gohan?

### ISSUE THREAD

**Issue by jdziat** [MelonFunction/ebiten-camera#1]
Would this be compatible with [Gohan](https://code.rocketnine.space/tslocum/gohan)?

**Comment by MelonFunction** [comment]
Ebiten-camera isn't built with ECS design in mind; it was created in a way that replicates the original source code a bit more directly. 
You could always wrap it in your own code or just edit/fork the source directly as there isn't an awful lot to it.
