### ISSUE TITLE
Why does `GetTranslation` automatically centers coordinates?

### ISSUE THREAD

**Issue by musjj** [MelonFunction/ebiten-camera#2]
Is there a reason why `GetTranslation` automatically centers the `GeoM` coordinates?

https://github.com/MelonFunction/ebiten-camera/blob/695003d18a6dcb8943c90c819d24cf018039cd32/camera.go#L92-L97

**Comment by MelonFunction** [comment]
There is no reason for it, other than it's convenient. Is this causing a problem for you?

**Comment by musjj** [comment]
I see. Well it's no blocker, but it was just really unexpected I guess. 

I'm new to Ebiten, and the behavior had me struggling with placing stuff at the right place with `DrawImage`. 

I'd expect that `GetTranslation` would *just* modify the coordinates and adjust it to the camera position, especially since you're expected to pass the `GeoM` to the standard `DrawImage` API anyways.

**Comment by MelonFunction** [comment]
Read my example code to understand how to use the library.

**Comment by musjj** [comment]
Maybe consider adding it to the list of `Considerations`? I've read the example code, but there's still no way to infer that coordinates are automatically centered.
